export const WORKFLOWS = [
  'company-comps','brand-inspiration','account-profiles','alt-data-aggregator','amex-cash-flow-forecast','billable-hours','brand-reputation','competitive-intelligence','account-outreach','company-initiation-report','competitive-landscape','compliance-monitor','content-creation','contract-review','customer-demo','draft-contract','due-diligence','etf-overlap','event-prep','expert-calls-analysis','finance-screener-workflow-fast','industry-overview','ipo-filings-analysis','key-driver-analysis','key-investor-debates-questions','keyword-generator','lbo','litigation-prep','macro-impact-analysis','management-kpi-credibility-tracker','management-sentiment-tracker','market-map','peer-earnings-read-through','post-earnings-report','pre-earnings-brief','update-investment-thesis','website-audit','create-product-requirements-document','data-exploration','sales-account-research','podcast','governance-multi-agent-verification'
];

export const MODE_FAMILIES = {
  'Truth & Verification': ['TRUTHMODE','FACTCHECK','VERIFY','CROSSCHECK','SOURCECHECK','PRIMARYSOURCES','PRIMARYSOURCEFIRST','OFFICIALSOURCEFIRST','ACADEMICFIRST','GOVERNMENTSOURCE','NOHALLUCINATION','NOINVENTION','EVIDENCEFIRST','FACTVSASSUMPTION','ASSUMPTIONCHECK','UNCERTAINTYCHECK','CONFIDENCECHECK','CONTRADICTIONCHECK','CONSISTENCYCHECK','REALITYCHECK','DATECHECK','CURRENCYDATECHECK','NUMBERSCHECK','CALCULATIONCHECK','UNITCHECK','SOURCEQUALITY','SOURCEINDEPENDENCE','CLAIMAUDIT','FINALVERIFICATION'],
  'Reasoning & Problem-Solving': ['FIRSTPRINCIPLES','DECOMPOSE','RECONSTRUCT','ROOTCAUSE','WHY5','SYSTEMTHINKING','CAUSALITY','DEPENDENCYMAP','LOGICMAP','PROBLEMDEFINITION','PROBLEMREFRAME','BACKWARDREASONING','FORWARDREASONING','SECONDORDERTHINKING','THIRDORDERTHINKING','DEEPRESEARCH','RESEARCHMODE','MULTISOURCE','CURRENTDATA','LATESTDATA','HISTORICALCONTEXT','COMPETITORRESEARCH','BENCHMARK','BESTPRACTICE','GLOBALBENCHMARK','LOCALBENCHMARK','ETHIOPIACHECK','INTERNATIONALCHECK','INDUSTRYSOURCE','MARKETDATA',],
  'Red Team & Adversarial': ['REDTEAM','REDTEAMMAX','DEVILSADVOCATE','CONTRARIAN','ATTACKTHEPLAN','BREAKTHEPLAN','BREAKTHESYSTEM','TRYTOFAIL','FAILUREMODE','WORSTCASE','BLACKSWAN','EDGECASE','ADVERSARIALMODE','ABUSECASE','THREATMODE','RISKMODE','VULNERABILITYMODE','GAPMODE','BLINDSPOTMODE','ASSUMPTIONATTACK','LOGICATTACK','SECURITYATTACK','BUSINESSMODELATTACK','FINANCIALATTACK','IMPLEMENTATIONATTACK','GAPCHECK','PREMORTEM','POSTMORTEM'],
  'Strategy & Business': ['STRATEGYMODE','STRATEGICFIT','VISIONCHECK','MISSIONCHECK','OBJECTIVECHECK','SWOT','PESTEL','PORTER5','VALUECHAIN','COMPETITIVEADVANTAGE','MOAT','SCENARIOPLANNING','STRATEGICOPTIONS','OPTIONVALUE','OPPORTUNITYCOST','PRIORITIZATION','ROADMAP','EXECUTIONSTRATEGY','BUSINESSMODEL','UNITECONOMICS','REVENUEMODEL','COSTMODEL','PRICINGMODEL','MARGINANALYSIS','BREAKEVEN','CUSTOMERLIFETIMEVALUE','CUSTOMERACQUISITION','RETENTION','CHURN','SCALABILITY','OPERATINGLEVERAGE','NETWORKEFFECT','VALUEPROPOSITION','BUSINESSMODELREDTEAM'],
  'Financial & Investment': ['FINANCIALMODE','FINANCIALAUDIT','MODEL_AUDIT','ASSUMPTIONAUDIT','REVENUEAUDIT','EXPENSEAUDIT','CAPEXCHECK','OPEXCHECK','WORKINGCAPITAL','CASHFLOW','LIQUIDITY','DEBT','LEVERAGE','DSCR','IRR','NPV','ROI','ROE','ROA','EBITDA','SENSITIVITY','SCENARIO','STRESS_TEST','DOWNSIDE','UPSIDE','BASECASE','FINANCIALREDTEAM','BANKINGMODE','INVESTORMODE','LENDERMODE','CREDITMODE','DUE_DILIGENCE','DDMODE','COMPS','VALUATION','DCF','LBO','M&A','EV_EQUITY_BRIDGE','SOURCES_USES','CAPTABLE','FINANCIAL_MODEL','INVESTMENTCASE','INVESTMENTTHESIS','DOWNSIDECASE','VALUATIONREDTEAM','INVESTORREDTEAM'],
  'Banking & Compliance': ['BANKSTRATEGY','BANKOPERATINGMODEL','COREBANKING','DIGITALBANKING','FINTECH','OPENBANKING','PAYMENTSMODE','CUSTOMEREXPERIENCE','CREDITRISK','MARKETRISK','LIQUIDITYRISK','OPERATIONALRISK','FRAUDRISK','CYBERRISK','AML_CHECK','KYC_CHECK','COMPLIANCE','GOVERNANCE','INTERNALCONTROL','AUDITMODE','RISKAPPETITE','CAPITALADEQUACY','ASSETQUALITY','NPLCHECK','TREASURY','ALM','IFB_CHECK','SHARIAH_GOVERNANCE','LEGALCHECK','REGULATORYCHECK','COMPLIANCECHECK','GOVERNANCEMODE','POLICYMODE','CONTRACTAUDIT','LICENSINGCHECK','DATAPRIVACY','RECORDKEEPING','AUDITTRAIL','SEGREGATIONOFDUTIES','CONFLICTCHECK','RISKCOMMITTEE','BOARDGOVERNANCE','REGULATORYREPORTING','ETHIOPIALAWCHECK','NBE_CHECK','TAXCHECK','COMMERCIALCODECHECK','DATA_PROTECTION_CHECK','LABORLAW_CHECK','INVESTMENTLAW_CHECK'],
  'Human Resources & Talent': ['EPMSMODE','HRMODE','TALENTMODE','COMPETENCYMODE','PERFORMANCEMODE','KPIENGINEERING','OKR','BALANCEDSCORECARD','COMPETENCYFRAMEWORK','SUCCESSIONPLANNING','CAREERPATH','LEARNINGPATH','COACHINGMODE','360FEEDBACK','PERFORMANCEANALYTICS','WORKFORCEANALYTICS','TALENTRISK','SKILLGAP','TRAININGNEEDS','LEADERSHIPPIPELINE'],
  'AI & Multi-Agent Systems': ['AIMODE','AGENTMODE','MULTIAGENT','AI_COUNCIL','AGENTORCHESTRATION','AGENTCOLLABORATION','AGENTDELEGATION','AGENTMEMORY','AGENTPLANNING','AGENTVERIFICATION','AGENTCRITIC','AGENTJUDGE','AGENTREDTEAM','HUMANINTHELOOP','AIHUMANLOOP','MODELENSEMBLE','CROSSMODELVERIFY','CONSENSUSMODE','DISAGREEMENTMODE','AIQUALITYGATE','AI_GOVERNANCE','AIMONITORING','AI_EVALUATION','VERIFICATIONLEDGER','AGENTCONSENSUS','AGENTDISSENT','GOVERNANCEGATE','RELEASEGATE'],
  'Architecture & Development': ['ARCHITECTUREMODE','ARCHITECTUREFIRST','SYSTEMDESIGN','MICROSERVICES','MODULARARCHITECTURE','EVENTDRIVEN','API_FIRST','DATABASEFIRST','DOMAINDRIVEN','SEPARATIONOFCONCERNS','SCALABILITY','HIGHAVAILABILITY','FAULTTOLERANCE','RESILIENCE','DISASTERRECOVERY','BACKUP','FAILOVER','OBSERVABILITY','MONITORING','LOGGING','TRACING','ARCHITECTUREAUDIT','SCALABILITYCHECK',],
  'Code & Development': ['CODEMODE','CODEAUDIT','CODEREVIEW','REFACTOR','CLEAN_CODE','SOLID','DRY','KISS','TYPE_SAFETY','ERROR_HANDLING','INPUT_VALIDATION','DEPENDENCY_AUDIT','TECHDEBT','DEADCODE','PERFORMANCEAUDIT','MEMORYSAFETY','CONCURRENCY','BACKWARDCOMPATIBILITY','MIGRATIONSAFETY'],
  'Security & Privacy': ['SECURITYMODE','SECURITYAUDIT','THREATMODEL','ATTACKSURFACE','ZEROTRUST','LEASTPRIVILEGE','DEFENSEINDEPTH','AUTHENTICATIONAUDIT','AUTHORIZATIONAUDIT','RBAC','ABAC','MFA','SSO','SESSIONSECURITY','SECRETSMANAGEMENT','ENCRYPTION','KEYMANAGEMENT','DATASECURITY','APISECURITY','DATABASESECURITY','NETWORKSECURITY','ENDPOINTSECURITY','SUPPLYCHAINSECURITY','DEPENDENCYSECURITY','VULNERABILITYSCAN','PENETRATIONTEST','OWASP_CHECK','SECRETS_SCAN','PRIVACY','DATAMINIMIZATION'],
  'Data Management & Auditing': ['DATAMODE','DATAAUDIT','DATAQUALITY','DATAINTEGRITY','DATACONSISTENCY','DATACLEANING','DATANORMALIZATION','SCHEMAAUDIT','DATABASEAUDIT','QUERYAUDIT','INDEXAUDIT','DATA_LINEAGE','DATA_GOVERNANCE','DATA_CLASSIFICATION','BACKUPCHECK','RECOVERYTEST','DUPLICATECHECK','NULLCHECK','ANOMALYCHECK','RECONCILIATION','PERFORMANCE',],
  'Testing & QA': ['TESTMODE','TESTALL','UNITTEST','INTEGRATIONTEST','SYSTEMTEST','E2ETEST','REGRESSIONTEST','SMOKETEST','SANITYTEST','LOADTEST','STRESSTEST','SECURITYTEST','FAILURETEST','CHAOSTEST','NEGATIVETEST','BOUNDARYTEST','ACCESSIBILITYTEST','MOBILETEST','CROSSBROWSER'],
  'UX & Product': ['UXMODE','UXAUDIT','UIAUDIT','USERJOURNEY','USERRESEARCH','USABILITY','SIMPLICITY','ZEROFRICTION','ACCESSIBILITY','MOBILEFIRST','RESPONSIVE','DESIGN_SYSTEM','INFORMATIONARCHITECTURE','NAVIGATIONTEST','ERRORMESSAGEAUDIT','ONBOARDING','CUSTOMERJOURNEY'],
  'Production & Deployment': ['PRODUCTIONMODE','PRODUCTIONREADY','DEPLOYMENTCHECK','RELEASECHECK','CI_CD','BUILD_CHECK','RUNTIME_CHECK','ENVIRONMENTCHECK','ENV_AUDIT','SECRETAUDIT','DOMAINCHECK','DNSCHECK','SSLCHECK','HEALTHCHECK','ROLLBACK','ALERTING','MONITORING','LOGGING','OBSERVABILITY',],
  'GitHub & Version Control': ['GITHUBMODE','REPOSITORYAUDIT','BRANCHAUDIT','PR_REVIEW','DIFFREVIEW','COMMITCHECK','ISSUECHECK','CICHECK','ACTIONSCHECK','SECRETSCAN','DEPENDENCYSCAN','CODEOWNERS','VERSIONCHECK','TAGCHECK','MERGECHECK'],
  'Deployment Platforms': ['VERCELMODE','DEPLOYMENTMODE','BUILDERROR','RUNTIMEERROR','NEXTJSAUDIT','SERVERLESS','EDGERUNTIME','APIAUDIT','ENVIRONMENTAUDIT','COREWEBVITALS','CACHING','RATE_LIMIT','CORS','SECURITYHEADERS','DOMAIN','DNS','SSL'],
  'Document & Investor QA': ['DOCUMENTQA','DECKQA','NUMBERSQA','SOURCEQA','FORMATTINGQA','CONSISTENCYQA','FOOTNOTEQA','CHARTQA','TABLEQA','EXECUTIVEQA','INVESTORREADINESS','BANKREADINESS','BOARDREADINESS','GOVERNMENTREADINESS','LENDERREADINESS'],
  'Perspective & Decision Modes': ['MANAGEMENTPERSPECTIVE','BOARDPERSPECTIVE','INVESTORPERSPECTIVE','BANKERSPERSPECTIVE','REGULATORPERSPECTIVE','ENDUSERPERSPECTIVE','BANKERMODE','BOARDMODE','CEOMODE','EXECUTIVEMODE','MANAGEMENTMODE','CFO_MODE','CTO_MODE','CISO_MODE','CHRO_MODE','AUDITCOMMITTEE','STRATEGYCOMMITTEE','DECISIONMODE','DECISIONSCIENCE','OPTIONANALYSIS','TRADEOFF','PROSCONS','EXPECTEDVALUE','PROBABILITY','UNCERTAINTY','DECISIONTREE','REVERSIBILITY'],
  'Ecosystem & Multi-Business': ['AURIONMODE','ECOSYSTEMMODE','HOLDINGCOMPANY','MULTIBUSINESS','VERTICALINTEGRATION','SUPPLYCHAIN','MARKETPLACE','B2B','B2C','B2G','CROSSBORDER','EXPORTMODE','MANUFACTURING','LOGISTICS','ECOMMERCE','TRADEFINANCE','PROCUREMENT','WAREHOUSE','FULFILLMENT','SETTLEMENT','ECOSYSTEMINTELLIGENCE','VALUECHAIN','FINTECH',],
  'Autonomous & Self-Improving': ['AUTONOMOUSMODE','SELFMONITORING','SELFDIAGNOSTIC','SELFTESTING','SELFHEALING','SELFOPTIMIZING','SELFUPDATING','SELFLEARNING','CONTINUOUSIMPROVEMENT','CONTINUOUSVALIDATION','CONTINUOUSSECURITY','CONTINUOUSDELIVERY','FEEDBACKLOOP','LEARNINGLOOP','PERFORMANCELOOP','HUMANOVERSIGHT','SAFEAUTONOMY','AUTONOMYBOUNDARIES'],
  'Mindset & Cultural Tags': ['369MODE','TESLAMODE','369YOU','TESLAYOU','369TEAM','TESLATEAM','FUTUREYOU','LINDYMODE','8020','YCOMBINATOR','HORMOZI','GARYVEE','HUMANMODE','REALWORLD','PRACTICALMODE','COMMONSENSE','CONTEXTMODE','STAKEHOLDERMODE','USERFIRST','CUSTOMERFIRST','EMPLOYEEFIRST'],
  'Final QA & Output': ['SELFCRITIQUE','FINALQA','FINALCHECK','EXECUTIVESUMMARY','ONEPAGE','DECISIONREADY','ACTIONORIENTED']
};

export const ALL_MODES = [...new Set(Object.values(MODE_FAMILIES).flat())];

export const ALIASES = {
  'MODEL AUDIT':'MODEL_AUDIT','MODELAUDIT':'MODEL_AUDIT','AI COUNCIL':'AI_COUNCIL','AICOUNCIL':'AI_COUNCIL',
  'KYC CHECK':'KYC_CHECK','KYCCHECK':'KYC_CHECK','AML CHECK':'AML_CHECK','AMLCHECK':'AML_CHECK','CI CD':'CI_CD','CICD':'CI_CD','CI/CD':'CI_CD',
  'DATA LINEAGE':'DATA_LINEAGE','DATALINEAGE':'DATA_LINEAGE','DATA GOVERNANCE':'DATA_GOVERNANCE','DATAGOVERNANCE':'DATA_GOVERNANCE',
  'API FIRST':'API_FIRST','APIFIRST':'API_FIRST','PR REVIEW':'PR_REVIEW','PRREVIEW':'PR_REVIEW','STRESS TEST':'STRESS_TEST','STRESSTEST':'STRESS_TEST',
  '/HUMAN':'HUMANMODE','HUMAN':'HUMANMODE','CFO MODE':'CFO_MODE','CTO MODE':'CTO_MODE','CISO MODE':'CISO_MODE','CHRO MODE':'CHRO_MODE',
  'GOVERNANCE MULTI AGENT VERIFICATION':'governance-multi-agent-verification',
  'GOVERNANCE-MULTI-AGENT-VERIFICATION':'governance-multi-agent-verification',
  'MULTI AGENT VERIFICATION':'governance-multi-agent-verification',
  'AGENT VERIFICATION':'AGENTVERIFICATION','AGENTVERIFICATION':'AGENTVERIFICATION',
  'AI GOVERNANCE':'AI_GOVERNANCE','AIGOVERNANCE':'AI_GOVERNANCE',
  'MULTI AGENT':'MULTIAGENT','MULTIAGENT':'MULTIAGENT',
  'CROSS MODEL VERIFY':'CROSSMODELVERIFY','CROSSMODELVERIFY':'CROSSMODELVERIFY',
  'GOVERNANCE GATE':'GOVERNANCEGATE','RELEASE GATE':'RELEASEGATE',
  'AGENT CONSENSUS':'AGENTCONSENSUS','AGENT DISSENT':'AGENTDISSENT',
  'VERIFICATION LEDGER':'VERIFICATIONLEDGER'
};

const PROFILES = {
  'company-comps':['COMPS','VALUATION','FINANCIALMODE','CURRENTDATA','SOURCECHECK','NUMBERSCHECK','FINALQA'],
  'due-diligence':['DEEPRESEARCH','FACTCHECK','FINANCIALAUDIT','LEGALCHECK','COMPLIANCECHECK','REDTEAMMAX','RISKMODE','CLAIMAUDIT','FINALQA'],
  'lbo':['LBO','LEVERAGE','CASHFLOW','IRR','SENSITIVITY','STRESS_TEST','MODEL_AUDIT','FINALQA'],
  'website-audit':['UXAUDIT','CODEAUDIT','SECURITYAUDIT','PERFORMANCEAUDIT','ACCESSIBILITYTEST','MOBILETEST','PRODUCTIONREADY','FINALQA'],
  'data-exploration':['DATAMODE','DATAQUALITY','ANOMALYCHECK','DUPLICATECHECK','NULLCHECK','RECONCILIATION','DATAAUDIT','FINALQA'],
  'competitive-intelligence':['DEEPRESEARCH','COMPETITORRESEARCH','STRATEGYMODE','VALUECHAIN','MOAT','REDTEAM','SOURCECHECK','FINALQA'],
  'compliance-monitor':['COMPLIANCECHECK','REGULATORYCHECK','CURRENTDATA','OFFICIALSOURCEFIRST','DATECHECK','FINALVERIFICATION'],
  'company-initiation-report':['DEEPRESEARCH','FINANCIALMODE','COMPS','DCF','INVESTMENTTHESIS','REDTEAMMAX','SOURCEQA','NUMBERSQA','FINALQA'],
  'contract-review':['CONTRACTAUDIT','LEGALCHECK','COMPLIANCECHECK','RISKMODE','CLAIMAUDIT','FINALQA'],
  'ipo-filings-analysis':['DEEPRESEARCH','FINANCIALAUDIT','CAPTABLE','VALUATION','CLAIMAUDIT','REDTEAMMAX','FINALQA'],
  'pre-earnings-brief':['CURRENTDATA','FINANCIALMODE','SENSITIVITY','INVESTORPERSPECTIVE','SOURCECHECK','NUMBERSCHECK','FINALQA'],
  'post-earnings-report':['CURRENTDATA','FINANCIALAUDIT','NUMBERSCHECK','INVESTMENTTHESIS','MANAGEMENTPERSPECTIVE','FINALQA'],
  'sales-account-research':['DEEPRESEARCH','FACTCHECK','CUSTOMERFIRST','ACTIONORIENTED','FINALQA'],
  'create-product-requirements-document':['DECOMPOSE','USERFIRST','SYSTEMTHINKING','USERJOURNEY','PRIORITIZATION','ROADMAP','DOCUMENTQA','FINALQA'],
  'governance-multi-agent-verification':['AI_GOVERNANCE','MULTIAGENT','AGENTORCHESTRATION','AGENTVERIFICATION','AGENTCRITIC','AGENTJUDGE','AGENTREDTEAM','CROSSMODELVERIFY','CONSENSUSMODE','DISAGREEMENTMODE','AIQUALITYGATE','HUMANINTHELOOP','TRUTHMODE','FACTCHECK','SOURCECHECK','CONTRADICTIONCHECK','CLAIMAUDIT','FINALVERIFICATION','AUDITMODE','AUDITTRAIL','FINALQA','VERIFICATIONLEDGER','AGENTCONSENSUS','AGENTDISSENT','GOVERNANCEGATE','RELEASEGATE']
};
for (const wf of WORKFLOWS) if (!PROFILES[wf]) PROFILES[wf] = ['TRUTHMODE','RESEARCHMODE','FACTCHECK','FINALQA','ACTIONORIENTED'];
export const WORKFLOW_PROFILES = Object.freeze(PROFILES);

export const CONNECTORS = [
  'ABRAMS Trade Intelligence','AI Business Plan by PrometAI','AI Vibe Prospecting','AJAXX Data Scrubber','Academic Writing Toolkit','AccessOwl','Acumen by Talarion','Ahrefs','Airtable','Almosafer.com','Ansvar Gateway','Apollo.io','Attio','Ballpark','Bitdefender','Business Helper','Business Strategy Builder','Canva','Catchr','CertScore.ai Privacy Scanner','Certifier','Chapka','CheapOair','Clay','Clutch.co','Coda','Code Tytor','Consensus','Context7','Datasite','Exa','Fireflies','Flight Network','ForeFlight Mobile','FullEnrich','GitHub','Gmail','Google Calendar','Google Contacts','Google Drive','Granola','HubSpot','IHG Hotels & Resorts','Is It Legit by M8ven','Kiwi.com','Linear','Loft','Lusha','Maersk','Magnific','MakeMyTrip','Malwarebytes','Microsoft Outlook Calendar','Microsoft Outlook Email','Microsoft SharePoint','Minty','Mixmax','Neon','Neura Relay MCP','Notion','Octopart Component Finder','Orbismo','Plugin Management','PostHog','Prezi','PrivacyHawk','ProofX','Quartr','Radar Lite','SIXT','Sanity','Shopify','Skyscanner','Supabase','Systeme.io','Tariff Code Compliance','ToolCheck by M8ven','Travel 101','Trip.com','Ubersuggest','Vercel','WPWriter','Waldo','Webflow','Wego','Wikiloc','Wix','Zoho CRM','Zoom','Zoom Revenue Accelerator','eDreams','idealista','iubenda'
];

export const CONNECTOR_POLICY = Object.freeze({
  rule: 'use-only-when-available-authorized-relevant-permitted',
  doNotAssumeConnected: true
});

export const ENGINE_PIPELINE = Object.freeze([
  { id: 'truth', name: 'Truth Engine', modes: ['TRUTHMODE','FACTCHECK','VERIFY','CROSSCHECK','SOURCECHECK','CLAIMAUDIT','FINALVERIFICATION'] },
  { id: 'reasoning', name: 'Reasoning Engine', modes: ['FIRSTPRINCIPLES','DECOMPOSE','SYSTEMTHINKING','CAUSALITY','SECONDORDERTHINKING'] },
  { id: 'redteam', name: 'Red Team Engine', modes: ['REDTEAM','REDTEAMMAX','ATTACKTHEPLAN','BREAKTHEPLAN','TRYTOFAIL','STRESS_TEST','VERIFY'] },
  { id: 'strategy', name: 'Strategy', modes: ['STRATEGYMODE','BUSINESSMODEL','MOAT','COMPETITIVEADVANTAGE','EXECUTIONSTRATEGY'] },
  { id: 'finance', name: 'Finance', modes: ['FINANCIALMODE','DCF','IRR','NPV','UNITECONOMICS','STRESS_TEST'] },
  { id: 'operations', name: 'Operations', modes: ['EXECUTIONSTRATEGY','SUPPLYCHAIN','LOGISTICS','PRODUCTIONREADY'] },
  { id: 'domain', name: 'Domain Engine', modes: ['BANKINGMODE','HRMODE','AIMODE','AURIONMODE','LEGALCHECK'] },
  { id: 'architecture', name: 'Architecture Engine', modes: ['ARCHITECTUREFIRST','DATAAUDIT','CODEAUDIT','SECURITYAUDIT','UXAUDIT','TESTALL'] },
  { id: 'production', name: 'Production Engine', modes: ['GITHUBMODE','CI_CD','VERCELMODE','MONITORING','PRODUCTIONREADY'] },
  { id: 'finalqa', name: 'Final QA Engine', modes: ['SOURCECHECK','NUMBERSCHECK','LOGICMAP','SECURITYAUDIT','COMPLIANCECHECK','UXAUDIT','FINALQA','DECISIONREADY'] }
]);

export const MASTER_STACKS = Object.freeze({
  default: ['TRUTHMODE','HUMANMODE','REALWORLD','FIRSTPRINCIPLES','DECOMPOSE','RESEARCHMODE','PRIMARYSOURCEFIRST','FACTCHECK','ASSUMPTIONCHECK','CALCULATIONCHECK','REDTEAMMAX','DEVILSADVOCATE','FAILUREMODE','RISKMODE','SECURITYAUDIT','COMPLIANCECHECK','FINANCIALAUDIT','ARCHITECTUREAUDIT','DATAAUDIT','CODEAUDIT','TESTALL','PERFORMANCEAUDIT','UXAUDIT','SCALABILITYCHECK','PRODUCTIONREADY','SELFCRITIQUE','CROSSCHECK','FINALQA','FINALVERIFICATION','DECISIONREADY','ACTIONORIENTED'],
  aurion: ['AURIONMODE','ECOSYSTEMMODE','369MODE','TESLAMODE','FUTUREYOU','LINDYMODE','8020','FIRSTPRINCIPLES','TRUTHMODE','DEEPRESEARCH','ETHIOPIACHECK','GLOBALBENCHMARK','BUSINESSMODEL','UNITECONOMICS','FINANCIALMODE','INVESTORMODE','BANKERMODE','REGULATORYCHECK','REDTEAMMAX','SECURITYMODE','AIMODE','MULTIAGENT','AI_COUNCIL','ARCHITECTUREFIRST','DATAAUDIT','CODEAUDIT','UXAUDIT','TESTALL','PRODUCTIONREADY','SELFMONITORING','SELFTESTING','SELFOPTIMIZING','CONTINUOUSIMPROVEMENT','HUMANOVERSIGHT','FINALQA','DECISIONREADY','ACTIONORIENTED'],
  mindset: ['369MODE','TESLAMODE','369YOU','TESLAYOU','369TEAM','TESLATEAM','FUTUREYOU','LINDYMODE','8020','REDTEAM','YCOMBINATOR','HORMOZI','GARYVEE']
});

export const SKILL_FAMILIES = Object.freeze({
  'Research & verification': ['Deep Research','Search','due-diligence','competitive-intelligence','industry-overview','Context7','Exa','Consensus'],
  'Investment Banking': ['company-comps','lbo','due-diligence','ipo-filings-analysis','update-investment-thesis','pre-earnings-brief','post-earnings-report'],
  'Data Analytics': ['data-exploration','finance-screener-workflow-fast','alt-data-aggregator','key-driver-analysis'],
  'Product Design': ['create-product-requirements-document','website-audit','customer-demo','content-creation'],
  'Public Equity Investing': ['company-initiation-report','peer-earnings-read-through','management-sentiment-tracker','key-investor-debates-questions','etf-overlap'],
  'Sales & CRM': ['sales-account-research','account-outreach','account-profiles','event-prep'],
  'Engineering, AI & Cloud': ['governance-multi-agent-verification','website-audit','compliance-monitor'],
  'Security, Privacy & Compliance': ['compliance-monitor','contract-review','litigation-prep'],
  'Documents & Artifacts': ['content-creation','draft-contract','podcast']
});

export const CATALOG_VERSION = '2.1.0';
