export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  currency: string;
  unit: string;
  origin: string;
  type: "B2C" | "B2B" | "Both";
  badge?: string;
  description: string;
  traceId?: string;
  image?: string;
  carbonKg?: number;
};

export const products: Product[] = [
  {
    id: "cf-001",
    name: "Yirgacheffe Washed Coffee",
    category: "Agricultural Products",
    price: 18.5,
    currency: "USD",
    unit: "kg",
    origin: "Yirgacheffe, Ethiopia",
    type: "Both",
    badge: "Specialty",
    description: "High-altitude washed Arabica. Floral, citrus, clean cup. Fully traceable from cooperative to export.",
    traceId: "AUR-CF-8842",
    image: "/images/products/green-coffee-sack.jpg",
    carbonKg: 1.8,
  },
  {
    id: "cf-002",
    name: "Sidamo Natural Coffee",
    category: "Agricultural Products",
    price: 16.2,
    currency: "USD",
    unit: "kg",
    origin: "Sidamo, Ethiopia",
    type: "Both",
    description: "Natural process. Berry and chocolate notes. Export grade with digital passport.",
    traceId: "AUR-CF-7711",
    image: "/images/products/green-coffee-spill.jpg",
    carbonKg: 1.9,
  },
  {
    id: "cf-003",
    name: "Green Coffee – Cherries & Beans Set",
    category: "Agricultural Products",
    price: 22.0,
    currency: "USD",
    unit: "kg",
    origin: "Southern Ethiopia",
    type: "Both",
    badge: "Fresh Harvest",
    description: "Premium green coffee with visual lot photography of cherries and beans.",
    traceId: "AUR-CF-9021",
    image: "/images/products/coffee-cherries-plate.jpg",
    carbonKg: 1.7,
  },
  {
    id: "cf-004",
    name: "Roasted Coffee Selection",
    category: "Agricultural Products",
    price: 24.5,
    currency: "USD",
    unit: "kg",
    origin: "AURION Roastery",
    type: "B2C",
    badge: "Roasted",
    description: "Three roast levels from light to dark. Scooped and packaged under AURION quality control.",
    traceId: "AUR-CF-R-1120",
    image: "/images/products/roasted-coffee-scoops.jpg",
    carbonKg: 2.4,
  },
  {
    id: "tx-001",
    name: "Habesha Embroidered Jacket",
    category: "Ethiopian Specialties",
    price: 185,
    currency: "USD",
    unit: "piece",
    origin: "Traditional Artisan Cooperative",
    type: "B2C",
    badge: "Heritage",
    description: "Hand-embroidered formal jacket with traditional motifs. Modern cut, ceremonial quality.",
    traceId: "AUR-TX-4401",
    image: "/images/products/habesha-jacket.jpg",
  },
  {
    id: "tx-002",
    name: "Ceremonial Habesha Kemis",
    category: "Ethiopian Specialties",
    price: 220,
    currency: "USD",
    unit: "piece",
    origin: "Traditional Weavers",
    type: "B2C",
    badge: "Ceremonial",
    description: "White netela-style dress with colorful cross and geometric embroidery. Full traditional set.",
    traceId: "AUR-TX-4408",
    image: "/images/products/habesha-kemis.jpg",
  },
  {
    id: "tx-003",
    name: "Gold-Embroidered Formal Suit",
    category: "Ethiopian Specialties",
    price: 340,
    currency: "USD",
    unit: "set",
    origin: "AURION Heritage Collection",
    type: "B2C",
    badge: "Premium",
    description: "White formal suit with intricate gold and multicolour embroidery on shoulders and cuffs.",
    traceId: "AUR-TX-4415",
    image: "/images/products/habesha-embroidered.jpg",
  },
  {
    id: "bk-001",
    name: "Traditional Woven Baskets Set",
    category: "Ethiopian Specialties",
    price: 95,
    currency: "USD",
    unit: "set",
    origin: "Artisan Collective",
    type: "Both",
    description: "Hand-woven colorful baskets and trays. Fair-trade, cultural heritage products.",
    traceId: "AUR-BK-3302",
    image: "/images/products/woven-baskets.png",
  },
  {
    id: "nz-001",
    name: "Premium Hazelnuts",
    category: "Food & Specialty",
    price: 14.5,
    currency: "USD",
    unit: "kg",
    origin: "Highland Farms",
    type: "Both",
    description: "Cleaned and graded hazelnuts. Ready for retail or industrial use.",
    traceId: "AUR-NZ-2201",
    image: "/images/products/hazelnuts.jpg",
  },
  {
    id: "ch-001",
    name: "Fresh Chestnuts",
    category: "Food & Specialty",
    price: 9.8,
    currency: "USD",
    unit: "kg",
    origin: "Highland Groves",
    type: "Both",
    description: "Seasonal chestnuts, harvested at peak maturity.",
    traceId: "AUR-CH-2105",
    image: "/images/products/chestnuts-open.jpg",
  },
  {
    id: "sp-001",
    name: "Ethiopian Berbere Spice Blend",
    category: "Food & Specialty",
    price: 12.5,
    currency: "USD",
    unit: "250g",
    origin: "AURION Agro Processing",
    type: "Both",
    badge: "Bestseller",
    description: "Authentic berbere. Chili, fenugreek, korarima, cardamom.",
    traceId: "AUR-SP-1103",
    carbonKg: 0.4,
  },
  {
    id: "jw-001",
    name: "Heritage Gold Cross Pendant",
    category: "Jewelry",
    price: 420,
    currency: "USD",
    unit: "piece",
    origin: "AURION Jewelry Atelier",
    type: "B2C",
    badge: "Heritage",
    description: "18k gold, traditional Ethiopian motif, modern finish. Materials from responsible supply.",
    traceId: "AUR-JW-2201",
  },
];

export const categories = [
  "All",
  "Agricultural Products",
  "Jewelry",
  "Food & Specialty",
  "Ethiopian Specialties",
];
